### ISSUE TITLE
not compatible with python 3 + and bugs accurs

### ISSUE THREAD

**Issue by GooFace2** [ankitaggarwal011/FaceGrab#1]
thank you for sharing your code. I found it is not compatible eith python 3+ .
I tried to modifiy print . but the code gets the following error
File "facegrab.py", line 35
    except OSError, e:
                  ^
SyntaxError: invalid syntax

File "facegrab.py", line 66
    return
 File "facegrab.py", line 68
    def main():
      ^
SyntaxError: invalid syntax
thanks

**Comment by ankitaggarwal011** [comment]
Yes, the project doesn't support Python 3. However, it shouldn't be difficult to make it work in Python 3.

You will need to change the except syntax as well for Python 3.

except OSError, e: will become except OSError as e:

**Comment by ankitaggarwal011** [comment]
It would be good idea to add Python 3 support to this while maintaining Python 2 compatibility.
